devices([
   "iPhone 8 Plus",
   "iPhone 13 Pro Max",
   "iPad Pro (12.9-inch) (2nd generation)",
   "iPad Pro (12.9-inch) (5th generation)"
])

languages([
   "en-US"
])

scheme("DXMVVMCExampleUITests")

clear_previous_screenshots(true)
override_status_bar(true)

